package com.example.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

enum class AppLanguage {
    BANGLA, ENGLISH
}

object Translations {
    private val en = mapOf(
        "app_title" to "Amar Clothing POS",
        "role_select" to "Select Workspace Role",
        "salesman" to "Sales Assistant",
        "owner" to "Shop Owner",
        "home_pos" to "Sales POS",
        "products" to "Products",
        "reports" to "Reports",
        "settings" to "Settings",
        "search_hint" to "Search products by name/barcode...",
        "code" to "Product Code",
        "name" to "Product Name",
        "category" to "Category",
        "size" to "Size",
        "buy_price" to "Buying Price (Cost)",
        "sell_price" to "Selling Price (Retail)",
        "stock" to "Stock Qty",
        "add_product" to "Add New Product",
        "edit_product" to "Edit Product",
        "delete" to "Delete",
        "save" to "Save Details",
        "cancel" to "Cancel",
        "cart" to "Current Cart",
        "empty_cart" to "No items in cart",
        "discount" to "Discount Code/Offer (%)",
        "total" to "Total Amount",
        "net_payable" to "Net Payable",
        "payment_method" to "Payment Gateway",
        "cash" to "Cash Payment",
        "bkash" to "bKash QuickPay",
        "nagad" to "Nagad SmartPay",
        "rocket" to "Rocket InstantPay",
        "enter_phone" to "Enter Wallet Phone Number",
        "enter_pin" to "Enter 4-Digit Security PIN (Simulation)",
        "tr_id" to "Transaction ID (Optional)",
        "checkout" to "Confirm and Checkout",
        "checkout_success" to "Sale recorded successfully!",
        "printer_setup" to "Bluetooth Thermal Printer",
        "printer_status" to "Printer Status",
        "printer_disconnected" to "Disconnected",
        "printer_connected" to "Connected Successfully!",
        "printer_connect_btn" to "Pair Simulated 58mm Printer",
        "print_receipt" to "Print Formatted Receipt",
        "receipt" to "Sales Invoice",
        "date" to "Date",
        "cashier" to "Cashier",
        "qty" to "Qty",
        "subtotal" to "Sub-total",
        "profit_stats" to "Profit Status",
        "reports_analysis" to "Analytical Financial Reports",
        "daily" to "Daily (Today)",
        "weekly" to "Weekly (7 Days)",
        "monthly" to "Monthly (30 Days)",
        "yearly" to "Yearly (365 Days)",
        "total_sales" to "Total Revenue",
        "total_profit" to "Total Margin Profit",
        "sales_count" to "Transactions Done",
        "shop_logo" to "Shop Initials (Logo icon)",
        "shop_name" to "Boutique/Shop Name",
        "shop_tagline" to "Shop Tagline/Title",
        "shop_phone" to "Contact Number",
        "shop_address" to "Google Maps/Physical Address",
        "shop_footer" to "Receipt Bottom Message",
        "online_status" to "System Mode",
        "online" to "Online (Cloud active)",
        "offline" to "Offline (Edge database)",
        "apply" to "Apply",
        "bengali" to "বাংলা",
        "english" to "English",
        "role_pass" to "Enter Owner Security PIN",
        "access_error" to "Incorrect PIN! Owner space is private.",
        "submit" to "Authenticate",
        "add_stock" to "Add Stock",
        "discount_applied" to "Discount Applied: ",
        "insufficient_stock" to "Insufficient items in stock!",
        "items_list" to "Items details",
        "select_category" to "Select Tag Category",
        "product_photo" to "Select Product Styling Illustration",
        "enter_product_details" to "Insert Product Details",
        "required_field" to "Required field",
        "all_products" to "All Inventory Clothes"
    )

    private val bn = mapOf(
        "app_title" to "আমার বুটিক পিওএস",
        "role_select" to "ওয়ার্কস্পেস রোল নির্বাচন করুন",
        "salesman" to "বিক্রয় সহকারী (সেলসম্যান)",
        "owner" to "দোকানের মালিক",
        "home_pos" to "বিক্রি করুন (POS)",
        "products" to "পোশাক তালিকা",
        "reports" to "হিসাব-নিকাশ ও রিপোর্ট",
        "settings" to "দোকান সেটিংস",
        "search_hint" to "নাম বা বারকোড দিয়ে খুঁজুন...",
        "code" to "প্রোডাক্ট কোড (বারকোড)",
        "name" to "পোশাকের নাম",
        "category" to "ক্যাটাগরি",
        "size" to "সাইজ (মাপ)",
        "buy_price" to "ক্রয় মূল্য (খরচ)",
        "sell_price" to "বিক্রয় মূল্য (মূল্য)",
        "stock" to "স্টক পরিমাণ",
        "add_product" to "নতুন প্রোডাক্ট যোগ করুন",
        "edit_product" to "প্রোডাক্ট সংশোধন",
        "delete" to "মুছে ফেলুন",
        "save" to "তথ্য সংরক্ষণ করুন",
        "cancel" to "বাতিল করুন",
        "cart" to "চলতি কার্ট (ব্যাগ)",
        "empty_cart" to "কার্টে কোনো পোশাক নেই",
        "discount" to "ডিসকাউন্ট বা ছাড় (%)",
        "total" to "মোট বিল",
        "net_payable" to "পরিশোধযোগ্য নেট বিল",
        "payment_method" to "পেমেন্ট মাধ্যম",
        "cash" to "নগদ টাকা (ক্যাশ)",
        "bkash" to "বিকাশ পেমেন্ট",
        "nagad" to "নগদ পে",
        "rocket" to "রকেট ইনস্ট্যান্ট",
        "enter_phone" to "গ্রাহকের ওয়ালেট মোবাইল নম্বর",
        "enter_pin" to "৪-সংখ্যার পিন নম্বর দিন (সিমুলেশন)",
        "tr_id" to "ট্রানজেকশন আইডি (ঐচ্ছিক)",
        "checkout" to "রেকর্ড ও বিক্রি নিশ্চিত করুন",
        "checkout_success" to "বিক্রয় সফলভাবে সম্পন্ন ও সংরক্ষিত হয়েছে!",
        "printer_setup" to "ব্লুটুথ থার্মাল প্রিন্টার",
        "printer_status" to "প্রিন্টার স্ট্যাটাস",
        "printer_disconnected" to "সংযুক্ত নেই",
        "printer_connected" to "থার্মাল প্রিন্টার সংযুক্ত হয়েছে!",
        "printer_connect_btn" to "৫৮ মিমি সিমুলেটেড প্রিন্টার যুক্ত করুন",
        "print_receipt" to "রসিদ / মেমো প্রিন্ট করুন",
        "receipt" to "বিক্রয় রসিদ / ক্যাশ মেমো",
        "date" to "তারিখ",
        "cashier" to "ক্যাশিয়ার",
        "qty" to "পরিমাণ",
        "subtotal" to "উপ-মোট",
        "profit_stats" to "লাভের হিসাব",
        "reports_analysis" to "আর্থিক রিপোর্টিং ও এনালাইসিস",
        "daily" to "দৈনিক রিপোর্ট (আজ)",
        "weekly" to "সাপ্তাহিক রিপোর্ট (৭ দিন)",
        "monthly" to "মাসিক রিপোর্ট (৩০ দিন)",
        "yearly" to "বার্ষিক রিপোর্ট (৩৬৫ দিন)",
        "total_sales" to "মোট বিক্রয় (টাকা)",
        "total_profit" to "মোট লভ্যাংশ (টাকা)",
        "sales_count" to "মোট মেমো সংখ্যা",
        "shop_logo" to "দোকানের লোগো টেক্সট",
        "shop_name" to "দোকানের নাম (বুটিক)",
        "shop_tagline" to "দোকানের স্লোগান / টাইটেল",
        "shop_phone" to "যোগাযোগের ফোন নম্বর",
        "shop_address" to "দোকানের ঠিকানা",
        "shop_footer" to "রসিদের নিচের শুভেচ্ছা বার্তা",
        "online_status" to "সফটওয়্যার মোড",
        "online" to "অনলাইন মোড (ক্লাউড অ্যাক্টিভ)",
        "offline" to "অফলাইন মোড (লোকাল ডাটাবেস)",
        "apply" to "প্রয়োগ করুন",
        "bengali" to "বাংলা",
        "english" to "English",
        "role_pass" to "মালিকের ৪-সংখ্যার সিকিউরিটি পিন দিন",
        "access_error" to "ভুল পিন দিয়েছেন! মালিক ইন্টারফেসটি সুরক্ষিত।",
        "submit" to "প্রবেশ করুন",
        "add_stock" to "স্টক যোগ",
        "discount_applied" to "প্রদেয় ছাড়: ",
        "insufficient_stock" to "দুঃখিত, পর্যাপ্ত স্টক নেই!",
        "items_list" to "বিস্তারিত পোশাকসমূহ",
        "select_category" to "ক্যাটাগরি সিলেক্ট করুন",
        "product_photo" to "পোশাকের স্টাইল ইলাস্ট্রেশন সিলেক্ট করুন",
        "enter_product_details" to "পণ্যের বিবরণ যুক্ত করুন",
        "required_field" to "এই তথ্যটি আবশ্যক",
        "all_products" to "স্টকের মোট পোশাকসমূহ"
    )

    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.BANGLA -> bn[key] ?: en[key] ?: key
            AppLanguage.ENGLISH -> en[key] ?: key
        }
    }
}

val LocalAppLanguage = compositionLocalOf { AppLanguage.BANGLA }
